version: '3'
services:
  gdtc:
    image: gdtc/base:latest
    container_name: gdtc
    environment: 
      - POSTGIS_HOST=${POSTGIS_HOST}
      - POSTGIS_PORT=${POSTGIS_PORT}
      - POSTGIS_USER=${POSTGIS_USER}
      - POSTGIS_DATABASE=${POSTGIS_DATABASE}
      - POSTGIS_PASS=${POSTGIS_PASS}
      - GDTC_IN_VOL=${GDTC_IN_VOL}
      - GDTC_OUT_VOL=${GDTC_OUT_VOL}
      - GDTC_ACCESS_KEY=${GDTC_ACCESS_KEY}
      - GDTC_SECRET_KEY=${GDTC_SECRET_KEY}
      - GDTC_DEBUG=${GDTC_DEBUG}
    volumes:
      - ${LOCAL_IN_VOL}:/input
      - ${LOCAL_OUT_VOL}:/output
    stdin_open: true
    tty: true
  postgis:
    image: "mdillon/postgis"
    container_name: postgis
    ports:
      - "8432:5432"
    stdin_open: true
    tty: true
